<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Shift4
 * @package		Shift4_Shift4Payment
 * @copyright	Copyright (c) 2011 Shift4 Corporation (http://www.shift4.com)
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;

    if (!$this->getHideTitle()) {
    	echo $this->htmlEscape($this->getMethod()->getTitle());
	}

	if (count($cards) == 0):
		echo $this->__('<br />');
		echo $this->__('(Payment not yet received)');
	else:
?>
<div class="cards-list">
    <?php foreach ($cards as $key => $card): ?>
        <?php if ($showCount): ?>
            <span><?php echo sprintf($this->__('Credit Card %s'), $key + 1); ?></span>
        <?php endif;?>

        <table class="info-table<?php if ($showCount):?> offset<?php endif;?>">
            <tbody>
            <?php foreach ($card as $_label => $_value):?>
            <tr>
                <td><?php echo $this->escapeHtml($_label)?>:</td>
                <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endforeach; ?>
</div>
<?php endif; ?>