<?php $_helper = Mage::helper('storelocations'); ?>
<?php $is_pickup = $_helper->isPickupMode();?>
<div class="block block-progress opc-block-progress">
    <div class="block-title">
        <strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('billing', 'complete')): ?>
            <dt class="complete">
                <?php echo $this->__('Billing Address') ?> <span class="separator">|</span> <a href="#billing" onclick="checkout.accordion.openSection('opc-billing'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <address><?php echo $this->getBilling()->format('html') ?></address>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Billing Address') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if($is_pickup) : ?>
            <?php if ($this->getCheckout()->getStepData('pickup', 'is_show')): ?>
            <?php if ($this->getCheckout()->getStepData('pickup', 'complete')): ?>
                <dt class="complete">
                    <?php echo $this->__('Pickup at Store') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-pickup');return false;"><?php echo $this->__('Change') ?></a>
                </dt>
                <dd class="complete">
                    <?php $_store = $_helper->getPickupStoreLocation();?>
                    <address>
                        <?php echo $_store->getStoreName();?><br/>
                        <?php echo $_store->getStoreAddress();?>
                        <?php if($_store->getStoreAddress2() != ''): ?>
                        <br/><?php echo $_store->getStoreAddress2();?>
                        <?php endif?>
                        <br/> 
                        <?php echo $_store->getStoreCity(); ?>, 
                        <?php 
                        if($_store->getStoreStateId() != '') 
                            echo $_store->getRegionCode($_store->getStoreStateId()); 
                        else 
                            echo $_store->getStoreState();
                        ?> <?php echo $_store->getStoreZipcode(); ?>
                        <?php if($_store->getStoreTelephone()) :?>
                        <br/>
                        <?php echo $this->__('Phone'); ?>: <?php echo $_store->getStoreTelephone();?>
                        <?php endif;?>
                    </address>
                </dd>
            <?php else: ?>
                <dt>
                    <?php echo $this->__('Pickup at Store') ?>
                </dt>
            <?php endif; ?>
            <?php endif; ?>
        <?php else: ?>
            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
            <?php if($this->getCheckout()->getStepData('shipping', 'complete')): ?>
                <dt class="complete">
                    <?php echo $this->__('Shipping Address') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a>
                </dt>
                <dd class="complete">
                    <address><?php echo $this->getShipping()->format('html') ?></address>
                </dd>
            <?php else: ?>
                <dt>
                    <?php echo $this->__('Shipping Address') ?>
                </dt>
            <?php endif; ?>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
            <?php if($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
                <dt class="complete">
                    <?php echo $this->__('Shipping Method') ?> <span class="separator">|</span> <a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method'); return false;"><?php echo $this->__('Change') ?></a>
                </dt>
                <dd class="complete">
                    <?php if ($this->getShippingMethod()): ?>
                        <?php echo $this->getShippingDescription() ?>

                        <?php $_excl = $this->getShippingPriceExclTax(); ?>
                        <?php $_incl = $this->getShippingPriceInclTax(); ?>
                        <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                            <?php echo $_incl; ?>
                        <?php else: ?>
                            <?php echo $_excl; ?>
                        <?php endif; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>

                    <?php else: ?>
                        <?php echo $this->__('Shipping method has not been selected yet') ?>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dt>
                    <?php echo $this->__('Shipping Method') ?>
                </dt>
            <?php endif; ?>
            <?php endif; ?>
            
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if($this->getCheckout()->getStepData('payment', 'complete')): ?>
            <dt class="complete">
                <?php echo $this->__('Payment Method') ?> <span class="separator">|</span> <a href="#payment" onclick="checkout.accordion.openSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a>
            </dt>
            <dd class="complete">
                <?php echo $this->getPaymentHtml() ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo $this->__('Payment Method') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>
        </dl>
    </div>
</div>
