<ol <?php if ($this->getCollapsed() && !$this->getHasSelection()): ?>style="display:none" <?php endif ?>>
<?php $show = ($this->getItemsCount() > 1 || !Mage::getStoreConfig('amshopby/general/hide_one_value')) ?>
<?php if (0 == $this->getDisplayType() && $show): // default ?>
    <?php foreach ($this->getItems() as $_item): ?>
    	<?php if($_item->getCount() <= 0) : continue; endif; ?>    
        <li>

            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>

            (<?php echo $_item->getCount() ?>)
        </li>
    <?php endforeach ?>
<?php elseif (1 == $this->getDisplayType() && $show): // dropdown ?>
    <li>
        <select onchange="if (this.value) setLocation(this.value)" class="amshopby-select">
            <!-- uncomment to show Filter name in the dropdown <option value=""><?php echo $this->getName() ?></option>-->
            <option value=""></option>
            <?php foreach ($this->getItems() as $_item): ?>
            <option  <?php if (Mage::app()->getRequest()->getParam('price') == $_item->getValue()) echo "selected" ?> 
                value="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?> (<?php echo $_item->getCount() ?>)</option>
            <?php endforeach ?>
        </select>
    </li>
<?php elseif (3 == $this->getDisplayType()): // slider ?>
<?php
    $max = $this->_filter->getMaxPriceInt(); 
    $from = min($this->getPriceFrom(), $max);
    $to   = min($this->getPriceTo(), $max);
    
    if ($from < 0.01 && $to < 0.01){
        $to = sprintf('%.02f', $max);
    }
    $width = 170;
    
    $firstOffset =  $from * $width / $max;
    $secondOffset = $to * $width / $max; 
?>
    <li>
        <div id="amshopby-slider" class="slider">
            <div class="handle selected" style="left:<?php echo $firstOffset ?>px"></div>
            <div class="handle" style="left:<?php echo $secondOffset ?>px"></div>
        </div>
        <script type="text/javascript">
            amshopby_slider(<?php echo $width . ', ' . $firstOffset . ', '. $secondOffset . ', ' . $max ?>, 'amshopby-price-');
        </script>
    </li>     
<?php endif; ?>
<?php if (Mage::getStoreConfig('amshopby/general/price_from_to')):?>
        <li>
            <input type="text" size="2" value="<?php echo $this->getPriceFrom()?>" name="price_from" class="input-text" id="amshopby-price-from" /> - 
            <input type="text" size="2" value="<?php echo $this->getPriceTo()?>" name="price_to" class="input-text" id="amshopby-price-to"/>
            <button type="submit" title="<?php echo $this->__('Find')?>" class="form-button button amshopby-price-find" name="price_find" id="amshopby-price-btn"><span><span><?php echo $this->__('Find')?></span></span></button>
        </li> 
<?php endif ?>
<input type="hidden" id="amshopby-price-url" value="<?php echo Mage::helper('amshopby/url')->getFullUrl(array('price'=>'price-from,price-to'))?>" />
</ol>