<?php $_helper = $this->helper('catalog/output'); ?>

<?php
$_productId = $this->getParentBlock()->getProductId();
$_product = Mage::getModel('catalog/product');
$_product = $_product->load($_productId);

?>

<div class="product-shop">
    <div class="product-name">
    
    <?php echo $this->getChildHtml('tester') ?>
    
        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
    </div> 
    
    <div class="product_type_data group">
        <?php //echo $this->getChildHtml('product_type_data') ?>
    </div>            
      
 
    <div class="product-options-wrapper">

        
		<?php if ($_product->isSaleable() && $this->hasOptions()):?>
        	Has Options
        
            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
         
    </div>

    <?php //echo $this->getChildHtml('other');?>  
    

</div><!-- end .product-options-wrapper -->

<div class="product-img-box">
    <?php //echo $this->getChildHtml('media') ?>
</div>
<div class="clearer"></div>


